name: Find and Build APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build the project
      run: ./gradlew assembleDebug --stacktrace

    - name: SEARCH FOR APK FILES
      run: |
        echo "=== LISTING ALL APK FILES ==="
        find . -name "*.apk" -type f
        echo "=== BUILD OUTPUTS STRUCTURE ==="
        find . -path "*/build/outputs/*" -type f | head -20

    - name: Upload ANY APK found
      uses: actions/upload-artifact@v4
      with:
        name: built-apk-file
        path: "**/*.apk"
        if-no-files-found: error